name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pymdown-extensions
          
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
